### ISSUE TITLE
Add support for setting "includes" parameter for redeploy

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#10]
In the `vertx run` command, the `--redeploy` option takes a list of glob patterns to determine which files should be watched for changes and thus trigger a redeploy. Could this capability be exposed via the plguin?

**Comment by tsegismont** [comment]
In the next version version of the plugin, we will support both Vert.x 4 and Vert.x 5.

Vert.x 5 doesn't have a redeployment mode so we won't have a `redeploy` to use.
