### ISSUE TITLE
recompiling only changed source files on redeploy

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#11]
I have an issue where all source files and generated sources are being recompiled on every redeploy. This is quite time consuming on a large project. Is there a way to enable only changed source files being recompiled?

**Comment by tsegismont** [comment]
Can't reproduce, I see this if change only a resource file

```
[INFO] >>> maven-compiler-plugin:3.13.0:compile (default-compile) @vertx-starter
[INFO] Nothing to compile - all classes are up to date.
```
