### ISSUE TITLE
Vertx version support 

### ISSUE THREAD

**Issue by rrigoni** [reactiverse/vertx-maven-plugin#121]
Our project uses vertx 2.1.5, I'm trying to make the plugin to work but I'm getting this error:

`Error: Could not find or load main class io.vertx.core.Launcher`

I checked the classpath and thie `Launcher` class does not exist. 

Any suggestion? Is the maven plugin compatible with Vertx 2.1.5?

Thanks

**Comment by cescoffier** [comment]
The plugin is made for Vert.x 3.x
