### ISSUE TITLE
Add a generic exec mojo

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#14]
# The issue:

When working with polyglot projects and including `vertx-unit` as a dependency, a new launcher command is available: `test`. This newly available command cannot be executed as part of this plugin and will require a 2 step approach:

1. run vmp:package
2. invoke the command

The side effects are that for this approach one will have to package all test dependencies as normal dependencies (i.e.: `vertx-unit` and any other test scoped dependencies must be marked as non test)

As we have now to run 2 tasks, it kind of defeats the purpose of the plugin to some extent.

# What I'd like to have

A mojo that behaves exactly like run, but allows me to specify the `command` and the classpath scope.

The idea to behave exactly like `run` is that we could now do both hot reload for the application or even for tests, an example would be to work close to what many node people are used to, as their code is saved (in our case it could be after a compilation that updates the `target/classes`) we would re-run the tests.

Note that the example above will not work exactly as described as the default `test` command terminates the vert.x application at the end of the tests, but if it wouldn't then this would be possible.

**Comment by tsegismont** [comment]
No longer applicable with Vert.x 5
