### ISSUE TITLE
Turn off webjars unpacking by default

### ISSUE THREAD

**Issue by tsegismont** [reactiverse/vertx-maven-plugin#143]
Vert.x web is able to serve webjar content without extracting it to the webroot dir.

See https://www.webjars.org/documentation#vertx

There should be an option to turn it on.

**Comment by tsegismont** [comment]
Turning off webjars unpacking by default may break existing apps. So perhaps just a switch (enabled by default) is better.

**Comment by cescoffier** [comment]
I believe it’s acceptable. This feature was not heavily used, so should be fine if documented.

**Comment by tsegismont** [comment]
Fine, I'll update #146

**Comment by tsegismont** [comment]
@cescoffier PR updated
