### ISSUE TITLE
Address already in use when redeploy tag is true

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#16]
hello, i'm trying this plugin by making a simple verticle.
first i tried with `mvn clean compile vertx:run` and verticle runs fine, then i turn it off with CTRL + C.
when i try to run `with mvn clean compile vertx:run` again,
  appears `SEVERE: java.net.BindException: Address already in use: bind`

when i try with `<redeploy>false</ redeploy>` this is not the case anymore, but i want to use redeploy feature.

 is this the expected behavior?

**Comment by shawmanz32na** [comment]
I believe this is related to #8.
