### ISSUE TITLE
Log4j2 configuration not found in fat-jar

### ISSUE THREAD

**Issue by EnilPajic** [reactiverse/vertx-maven-plugin#163]
Hello,

I'm using `vertx-maven-plugin:1.2.0`, and Log4j2 (`2.11.2`) as one of my dependency. Also, one of my dependencies use Log4j2 as their dependency. So, everything works fine if I run my application via IntelliJ or `vertx:run`, but when I package it via `mvn clean package` or `mvn clean vertx:package` (for deployment, fabric8 is used), then Log4j2 is complaining, like this:

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
```
My `log4j2.xml` file is located in `src/main/resources` folder. Inspection of the fat-jar shows `log4j2.xml` in `.jar` file (also in `target/classes`), but somehow Log4j2 cannot find it. Also, additional properties (like path to config file) cannot be passed on server (I don't have control of this).

My research showed that transitive dependency of Log4j2 can create some cache files (like `Log4j2Plugins.dat`) that should be excluded from fat-jar. It seems that this is a common issue, please see this [log4j2 ticket](https://issues.apache.org/jira/browse/LOG4J2-673) (unfortunately, I cannot wait to log4j2 3.0.0 to be released). So far, every answer is for `maven-shade-plugin` (like [this](https://stackoverflow.com/questions/48033792) and [this](https://stackoverflow.com/questions/34945438/)), and I couldn't find anything similar for `vertx-maven-plugin`.

I read the documentation (especially [this](https://reactiverse.io/vertx-maven-plugin/#configuring-embedded-dependencies)), but couldn't figure it out.

My plugin declaration in `pom.xml` is following:
```
<plugin>
                <groupId>io.reactiverse</groupId>
                <artifactId>vertx-maven-plugin</artifactId>
                <version>1.0.20</version>
                <executions>
                    <execution>
                        <configuration>
                            <archive>
                                <dependencySets>
                                    <set>
                                        <options>
                                            <excludes>
                                                <exclude>**/META-INF/*.SF</exclude>
                                                <exclude>**/META-INF/*.DSA</exclude>
                                                <exclude>**/META-INF/*.RSA</exclude>
                                                <exclude>**/Log4j2Plugins.dat</exclude>
                                                <exclude>**/*.dtd</exclude>
                                                <exclude>*.dtd</exclude>
                                                <exclude>**/*.xsd</exclude>
                                                <exclude>**/*.xml</exclude>
                                                <exclude>*.dat</exclude> <!-- should exclude it, right? -->
                                            </excludes>
                                        </options>
                                    </set>
                                </dependencySets>
                            </archive>
                        </configuration>
                        <id>vmp</id>
                        <goals>
                            <goal>initialize</goal>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <redeploy>true</redeploy>
                </configuration>
 </plugin>
```

What I'm doing wrong? Thanks in advance!

**Comment by tsegismont** [comment]
Thanks for your report.

Plugin files shouldn't be excluded (this is why you get the `ERROR` messages in the logs). Instead, they should be merged. Unfortunately, log4j2 uses a binary format and there is no standard transformer for them. You may use this project though:

https://github.com/edwgiz/maven-shaded-log4j-transformer

Otherwise you can switch to logback, it works very well with fat jars.

**Comment by tsegismont** [comment]
@EnilPajic closing as there is not much we can do. This is a log4j2 issue that will be addressed in a future log4j2 version.

**Comment by EnilPajic** [comment]
@tsegismont okay, thank you for your comment!

Unfortunately I didnt find anything in the docs on how to use transformers (like https://github.com/edwgiz/maven-shaded-log4j-transformer) in vertx-maven-plugin (there are many examples on the internet for maven-shade-plugin). If you can point me in the right direction?

Again, thank you!

**Comment by tsegismont** [comment]
@EnilPajic my bad, I thought it was possible to customize the plugin with any transformer. I filed #164

**Comment by tsegismont** [comment]
Reopening after closing #164 .
