### ISSUE TITLE
[enhancement] Feedback improvement when vertx.verticle is missing

### ISSUE THREAD

**Issue by vision8tech** [reactiverse/vertx-maven-plugin#18]
Hello everybody!

As a suggestion, one small improvement would be to provide the right feedback in case `vertx.verticle` property is missing. By default, currently if this property is not included (at least in `pom.xml`), the error thrown is the effect, not the root cause:
```bash
java.lang.ClassNotFoundException: redeploy-termination-period=1000
```

What do you think?

Thanks

**Comment by cescoffier** [comment]
Yes, a better error message is required.

**Comment by cescoffier** [comment]
It's going to provide such kind of error message:

```
Invalid configuration, the element `verticle` (`vertx.verticle` property) is required if the element `launcher` (`vertx.launcher` property) is not set (or is `io.vertx.core.Launcher`)
```

**Comment by vision8tech** [comment]
Nice! 👍  Thanks!
