### ISSUE TITLE
Add an option to exclude dependencies from the packaging

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#2]
The package mojo should have an options to filter out some dependencies. Here some thoughts about how it can look like:

```
<excludes>
  <exclude>org.acme:foo</exclude> <- exclude all the dependencies using its groupId:artifactId (regardless the classifier)
  <exclude>org.acme:foo:fat</exclude> <- exlude the dependency using its groupId:artifactId:classifier
  <exclude>org.acme</exclude> <- exclude all dependencies with the matching groupId
```

I'm not sure we need to be complete in the sense that if the fat jar packaging is complex too complex, it should use a specific maven plugin (shader)

**Comment by gaol** [comment]
@cescoffier is this still a valid issue? I can help with it if possible. :)

**Comment by cescoffier** [comment]
@gaol yes, this issue is still valid. some preparation work has been done to the `archive` object can be easily customized. Right now this parameter is hidden (not accessible), I'd like to make is accessible to the users very soon.

Archive configuration allows:

* fine tuning of the set of dependencies
* select files from dependencies
* embed file and file sets
* better configuration of the `service` descriptor combination

**Comment by gaol** [comment]
@cescoffier cool. :) 
BTW, if you have anything that needs any assistance, I can try to help :smile:

**Comment by cescoffier** [comment]
@gaol PRs of any of the reported issue is more than welcome!

**Comment by cescoffier** [comment]
The plugin now has an `archive` attribute that can configure dependency sets. Each set can include/exclude dependencies.
