### ISSUE TITLE
Unable to detect source changes in internal dependent modules

### ISSUE THREAD

**Issue by changchengqin** [reactiverse/vertx-maven-plugin#202]
My project uses maven multi-modules, the project structure is as follows:

project
-  pom.xml
-  A
   - pom.xml
-  B
   - pom.xml

Where A depends on B

After starting the submodule A with the following command in the project root directory, I tried to modify any source code file in submodule B. vertx-maven-plugin does not have redeploy.
> mvn clean compile vertx:run -pl A -am

**Comment by tsegismont** [comment]
@changchengqin reloading the app when a dependency changes is not supported currently

**Comment by changchengqin** [comment]
OK，thks
