### ISSUE TITLE
Windows 10 is deprecating wmic, so should we use Get-CimInstance  to replace it?

### ISSUE THREAD

**Issue by chengenzhao** [reactiverse/vertx-maven-plugin#205]
In method io.vertx.core.impl.launcher.commands.StopCommand.terminateWindowsApplication:

```java
  private void terminateWindowsApplication() {
    // Use wmic.
    List<String> cmd = Arrays.asList(
        "WMIC",
        "PROCESS",
        "WHERE",
        "CommandLine like '%vertx.id=" + id + "%'",
        "CALL",
        "TERMINATE"
    );
```

since WMIC is about to sunset in future, and already deprecated in Win 10, one of our interns are using win 10 and found this issue, so should we use Get-CimInstance to replace it?

reference: https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated

**Comment by tsegismont** [comment]
@chengenzhao can you please post this to vertx-core? This is actually not specific to the Vert.x Maven plugin. Ping me in the comments please. Thank you
