### ISSUE TITLE
Java 9 Debug In Docker Container

### ISSUE THREAD

**Issue by sstubbs** [reactiverse/vertx-maven-plugin#31]
I have been using the debug option in java 8 with no issues. After upgrading to java 9 it needs the debugging port set to *:5005 in order to debug it from hosts other than localhost but -Ddebug.port=5005 only accepts a number I have tried setting it to to *:5005 which results in an error. I have also tried using the run command and passing in jvm args but I am also unable to get this to work.

**Comment by sstubbs** [comment]
I have changed the debugPort to a string in the DebugMojo file but I can't push to a new branch on this  repo. All tests run though. Perhaps you can make the change otherwise let me know if there is anything else you would like me to do.

**Comment by cescoffier** [comment]
Closed by https://github.com/reactiverse/vertx-maven-plugin/pull/33.
