### ISSUE TITLE
Changelog/Release notes?

### ISSUE THREAD

**Issue by yeikel** [reactiverse/vertx-maven-plugin#586]
Hi there

Do we publish release notes and/pr changelog for this project anywhere? 

For example, while trying to upgrade from 1.0.28 to 1.0.29, I could not find what changed easily

The Diff is always an option but that is not ideal: https://github.com/reactiverse/vertx-maven-plugin/compare/v1.0.28...v1.0.29

**Comment by tsegismont** [comment]
Hi!

You can see the list of issues/PR related to the milestone on GH: https://github.com/reactiverse/vertx-maven-plugin/milestone/11?closed=1
