### ISSUE TITLE
Adding destFileName to vertx-web-client.js file

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#6]
traditionally the vertx-web-client.js are being called `vertx-eventbus.js`, hence will it be nice to add option to allow the destfile name for web client javascript files via plugin ? 

some thing like 
```
<webrootDestFiles>
    <vertx-web-client>vertx-eventbus</vertx-web-client>
    <jquery>my-jquery</jquery>
</webrootDestFiles>
```
so when the initialize goal executes - it will copy `vertx-web-client --> vertx-eventbus` and `jquery --> my-jquery` with extensions as is

@cescoffier  - thoughts ?

**Comment by pmlopes** [comment]
Does it make sense to handle frontend builds with maven instead of leaving the user to use her own favourite frontend tool? I mean if you're really using js frameworks you will pull those dependencies from NPM/CDN network?

**Comment by cescoffier** [comment]
@pmlopes We have received requests to handle them. So there is a need. We also have an example showing how you can use NPM and Bower with the Vert.x Maven Plugin. But it's not that easy to set up.

**Comment by cescoffier** [comment]
This is not required anymore. The plugin has now an `archive` attribute that can include specific files where the output directory and destination name can be configured.
