### ISSUE TITLE
Support adding fabric8 maven plugin during setup

### ISSUE THREAD

**Issue by rdruss** [reactiverse/vertx-maven-plugin#78]
Setup has the ability to generate a pom.xml file if you do not have one.  It may be useful to include a way (perhaps an argument) to indicate whether you want to include the fabric8 maven plugin in our pom.xml file.  This will make it easy to create a Vert.x application from scratch and be ready to deploy it to OpenShift.

**Comment by tsegismont** [comment]
The FMP is deprecated
